services:
  - type: web
    name: my-app-web
    runtime: static
    buildCommand: bash build.sh
    staticPublishPath: build/web
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Cache-Control
        value: no-cache
