staticSites:
  - name: fest-flutter-web
    buildCommand: bash build.sh
    publishPath: build/web
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
